
checks:
  ignorePaths:
    - "/home/runner/work/konflux-ci/konflux-ci/.kube-linter/out-dependencies-keycloak-deployment.yaml"
    - "/home/runner/work/konflux-ci/konflux-ci/.kube-linter/out-dependencies-registry.yaml"
    - "/home/runner/work/konflux-ci/konflux-ci/.kube-linter/out-dependencies-tekton-results.yaml"

  include: [ ]

  exclude: 
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "env-var-secret"
    - "liveness-port"
    - "readiness-port"
    - "startup-port"
    - "non-existent-service-account"
    - "latest-tag"
